FROM nginx:1.25.4

COPY ../default_cover/cover-original.png /www/html/cover-original.png
COPY ../default_cover/cover-lg.png /www/html/cover-lg.png
COPY ../default_cover/cover-sm.png /www/html/cover-sm.png