FROM node:lts-alpine as buildstep
COPY ./storyteller /var/source
WORKDIR /var/source
RUN npm install --verbose
RUN npm run build
FROM nginx:1.25.4 as runstep
COPY --from=buildstep /var/source/dist/storyteller/browser /www/data/storyteller